### ISSUE TITLE
Desired: Ability to query (filtered) workflows for a project.

### ISSUE THREAD

**Issue by eddiewebb** [CircleCI-Public/api-preview-docs#16]
Current Preview endpoints include specific workflows (GET /workflow/:id) and project details (GET /project/:project_slug)  but no way to get the list of workflows for a project.  This feels like a gap given our V1 API allowed all jobs for a project, and without a listing/index I don't understand where the workflow_ID would come from unless running inside a job.

This endpoint is important for essentially any API call that needs to discover workflow IDs, statuses, etc.

It would be particularly useful for my Queuing orb to understand all running workflows for the current project since querying individual jobs can have a race condition in the transitions between jobs.  https://github.com/eddiewebb/circleci-queue/issues/26

**Comment by ndintenfass** [comment]
We are likely to first add a way to list recent pipelines, each of which would know its workflow IDs. We might also add a way to query directly to recent workflows for a project and/or triggerer, but that's still TBD.

**Comment by eddiewebb** [comment]
A listing of all pipelines (ideally still supporting the filters, including *date* :D)  that included their workflow IDs would be perfectly sufficient for my use cases.

**Comment by ndintenfass** [comment]
@eddiewebb you can now retrieve recent pipelines for a project using `GET /project/:project_slug/pipeline/`

**Comment by eddiewebb** [comment]
Woot!   

- Any filtering (date, status, etc)?  
- What constitutes "recent"?

https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/api-changes.md#get-projectproject_slugpipeline is light on details.

**Comment by ndintenfass** [comment]
We don’t yet have any filtering. Recent really means ordered descending by date. The endpoint is paginated.
