### ISSUE TITLE
Desired: Run a pipeline on a specified branch

### ISSUE THREAD

**Issue by tahir-wasim** [CircleCI-Public/api-preview-docs#30]
Currently we have an endpoint to which you can make a POST request:
`POST /project/:project_slug/pipeline`.  This runs a pipeline on a default branch.  Is it possible to run a pipeline on a specified branch, using the 1.1 structure? eg.
`POST /project/:project_slug/tree/:branch/pipeline`

**Comment by sulami** [comment]
You can include a payload on the v2 post request like this:

{“branch”: “feature/foo”}

And that will trigger a pipeline for the branch you name instead of the default branch.

Robin Schroer

**Comment by KhadijaAmmar** [comment]
> You can include a payload on the v2 post request like this: {“branch”: “feature/foo”} And that will trigger a pipeline for the branch you name instead of the default branch. Robin Schroer
> […](#)
> On 28 Jun 2019, 21:33 +0200, Tahir Wasim ***@***.***>, wrote: Currently we have an endpoint to which you can make a POST request: POST /project/:project_slug/pipeline. This runs a pipeline on a default branch. Is it possible to run a pipeline on a specified branch, using the 1.1 structure? eg. POST /project/:project_slug/tree/:branch/pipeline — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Are you sure it will trigger on a specific branch? that doesn't work for me and it's always triggering the default branch

**Comment by sulami** [comment]
I'm not sure why this isn't showing on GitHub, but I checked on our current cloud environment, and it indeed works as intended for my test repo. The exact request I'm sending is this:

curl -i -H Circle-Token\:\ <token> -H Accept\:\ application/json -H Content-Type\:\ application/json -XPOST https\://circleci.com/api/v2/project/github/sulami/cci-test/pipeline -d \{'
'\ \ \"branch\"\:\ \"foobar\"\,'
'\}'
'

Sorry about the crazy escaping, this code is generated, but I confirmed it works if you just paste it into a shell.

--

Robin Schroer
