### ISSUE TITLE
Desired: ability to use `unless` key

### ISSUE THREAD

**Issue by aamorozov** [CircleCI-Public/api-preview-docs#34]
My use case is that I have 2 workflows and I would like to run only one of them based on the api call, and run only the second one based on the trigger from github. 
Currently, when using unless it gives me the following config error:
```
#!/bin/sh -eo pipefail
# Config does not conform to schema: {:workflows {:build_deploy_frontend_backend {:unless disallowed-key}}}
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
Exited with code 1
```

**Comment by ndintenfass** [comment]
Unless is coming soon - hopefully will be live in a few days.

**Comment by aamorozov** [comment]
🎉 Thank you! If somebody comes to this issue, i ended up applying a workaround with creating another parameter that defaulted to true, and just setting that parameter in the api call for the workflow I don't want to run.

**Comment by stianfredriksen** [comment]
@ndintenfass Any updated on `unless`? I see you said it would hopefully live in a _few_ days? :)

**Comment by sulami** [comment]
@stianfredriksen I just PR'd `unless`, so I'm hoping it'll be live by tomorrow.

**Comment by ndintenfass** [comment]
`unless` should now work in production under a workflow. It is the inverse of `when`
