### ISSUE TITLE
Backport note about Accept header to v1 docs

### ISSUE THREAD

**Issue by lucas42** [CircleCI-Public/api-preview-docs#38]
At the bottom of your preview docs for v2 API it says:

> If you do not provide an ACCEPT header, the v2 API will return JSON. This is a change from 1.1, which would default to EDN.

This is a really useful bit of information that I spent ages struggling with when using the v1 API.  Would it be possible for that to be added to the docs for v1?  I couldn't find mention of it anywhere.  (Apologies if this is wrong place to mention this - I know you're probably focusing on the new API, and less about the existing one)

**Comment by ndintenfass** [comment]
Thanks for this. I’m closing it here, but I have passed this feedback along to our docs team who owns the 1.1 API docs.
