### ISSUE TITLE
Paging control on pipeline API

### ISSUE THREAD

**Issue by robcresswell** [CircleCI-Public/api-preview-docs#48]
Is there a way to control the paging (if any?) on the pipeline API? For example, can I request 100 at once? Can I request item 100 - 200? etc

I'm aware of the next page token, but it doesnt seem to be otherwise documented

**Comment by jama22** [comment]
Unfortunately, there isn't a way to set the page size on the API response in the v2 API

**Comment by robcresswell** [comment]
That's a shame, but thanks for the reponse :smile:
