### ISSUE TITLE
Changefeed?

### ISSUE THREAD

**Issue by robcresswell** [CircleCI-Public/api-preview-docs#55]
Probably the biggest addition from my point of view would be the ability to subscribe to some sort of changes or event driven API; maybe an arbitrary webhook? At the moment the best thing I could figure out is polling and parsing the data.

**Comment by ndintenfass** [comment]
Agree this would be powerful -- it's definitely on our list of Problems to solve, as the polling that is all-but required today is not very satisfying. That said, it's a non-trivial concern that currently sits b behind several other additions to the API, so I can't make any statements about timing.

**Comment by robcresswell** [comment]
No worries; glad to hear its being considered anyway. Thanks @ndintenfass! I'll close this
