### ISSUE TITLE
Triggering Workflows with boolean parameters no longer works 

### ISSUE THREAD

**Issue by philnielsen** [CircleCI-Public/api-preview-docs#57]
I've been toying with running a bot to trigger conditional workflows via slack (as described by the [the docs](https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/conditional-workflows.md)) As of this morning, boolean parameters are being automatically converted into strings. previously working curl command:

```bash
curl -X POST \
  'https://circleci.com/api/v2/project/:projectslug/pipeline?circle-token=TOKEN' \
  -H 'Content-Type: application/json' \
  -d '{"parameters": {"mark": true} }'
```
error in circle
```bash
#!/bin/sh -eo pipefail
# Type error for argument mark: expected type: boolean, actual value: \"true\" (type string)
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
Exited with code 1
CircleCI received exit code 1
```

**Comment by ndintenfass** [comment]
We think this was transient and now fixed. Please try again.

**Comment by philnielsen** [comment]
Yep, seems to be fixed now, thanks! @ndintenfass
