### ISSUE TITLE
Cannot access job output

### ISSUE THREAD

**Issue by nbedos** [CircleCI-Public/api-preview-docs#80]
I can't seem to find a way to access job logs using API V2.

For v1.1 the following query returns the job including all actions with their `"output_url"` attribute. Perfect!
```shell
curl -H 'Content-Type: application/json' "https://circleci.com/api/v1.1/project/gh/nbedos/citop/37?circle-token=$CIRCLECI_API_TOKEN"
```

However the corresponding query using API V2 returns much less information. No job step, no action, no `"output_url"`.
```shell
curl -H 'Content-Type: application/json' "https://circleci.com/api/2/project/gh%2Fnbedos%2Fcitop/job/37?circle-token=$CIRCLECI_API_TOKEN"
```

Am I missing something? How can I get the log of a job using API V2? I tried a few other endpoints without success.

Thanks

**Comment by nbedos** [comment]
@jama22 Any thoughts on this? Is this an intended breaking change?

**Comment by plimpton** [comment]
This is still needed. Should not have been auto closed
