### ISSUE TITLE
Workflow jobs and Workflow runs documentation

### ISSUE THREAD

**Issue by Fgerthoffert** [CircleCI-Public/api-preview-docs#90]
Hi,

When calling: `https://circleci.com/api/v2/insights/{project-slug}/workflows/{workflow-name}/jobs/{job-name}` or `https://circleci.com/api/v2/insights/{project-slug}/workflows/{workflow-name}`

The documentation specifies `credits-used` but the payload is actually `credits_used` (see below).

The payload received is:
```json
    {
      "id": "REMOVED",
      "started_at": "2020-03-19T03:20:55.139Z",
      "stopped_at": "2020-03-19T03:25:23.275Z",
      "duration": 268,
      "status": "success",
      "credits_used": 44
    },
```

**Comment by da-art85** [comment]
`[👀](url)`

**Comment by sulami** [comment]
@millerpeterson you might be interested in this.

**Comment by millerpeterson** [comment]
Thanks I'll address this.

**Comment by millerpeterson** [comment]
Updated the docs to show the correct field name `credits_used`.
