### ISSUE TITLE
Typo in CircleCI API v2 Docs

### ISSUE THREAD

**Issue by vinitshahdeo** [CircleCI-Public/api-preview-docs#96]
![Screenshot 2021-04-12 at 12 24 17 AM](https://user-images.githubusercontent.com/20594326/114317433-b5bba180-9b25-11eb-8b87-7174194a54a8.png)

In API v2 Developer's guide page, the [Gather Insights](https://circleci.com/docs/2.0/api-developers-guide/?section=reference#gather-insights) section has a typo. It should be **containing**, not **containg**.

**Comment by sulami** [comment]
Hi Vinit,

Those docs live over at https://github.com/circleci/circleci-docs.

**Comment by vinitshahdeo** [comment]
Thanks @sulami. Created an [issue](https://github.com/circleci/circleci-docs/issues/5237) there.
