### ISSUE TITLE
typo in orb reference in docs

### ISSUE THREAD

**Issue by josh-mcq** [CircleCI-Public/api-preview-docs#99]
https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/setup-workflows.md#full-example

```
orbs:
  continuation: circleci/continuation:0.1.2
```
i believe should be:  ('@' symbol)
```
orbs:
  continuation: circleci/continuation@0.1.2
```

**Comment by sulami** [comment]
Indeed, good catch!

**Comment by Psoffie009** [comment]
> https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/setup-workflows.md#full-example
> 
> ```
> orbs:
>   continuation: circleci/continuation:0.1.2
> ```
> 
> i believe should be: ('@' symbol)
> 
> ```
> orbs:
>   continuation: circleci/continuation@0.1.2
> ```

**Comment by Psoffie009** [comment]
> Indeed, good catch!
